securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

tags:
  - Applications
summary: Create a new job application, Candidates Only.
description: Endpoint to create a new job application. The user must be authenticated, and the request data must contain the details of the application. Returns a JSON response containing the details of the created application, or an error message if the application could not be created.
operationId: createApplication
security:
  - bearerAuth: []
parameters:
  - in: body
    name: body
    schema:
      type: object
      properties:
        job_id:
          type: string
          description: The ID of the job to apply for
responses:
  201:
    description: Application created successfully
    examples:
      application/json:
        {
          "status": "success",
          "message": "Application created successfully",
          "data":
            {
              "id": "application1",
              "job_id": "job1",
              "candidate_id": "candidate1",
              "status": "applied",
            },
        }
  401:
    description: Unauthorized access
    examples:
      application/json:
        { "status": "error", "message": "Unauthorized", "data": {} }
  400:
    description: Invalid input or job not found or already applied
    examples:
      application/json:
        {
          "status": "error",
          "message": "Invalid input or job not found or already applied",
          "data": {},
        }
