securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

tags:
  - Applications
summary: Fetch one or all job applications
description: Endpoint to fetch the details of one or all job applications. The user must be authenticated. If an application ID is provided, the details of that specific application are returned. If no application ID is provided, the details of all applications are returned. Returns a JSON response containing the details of the fetched application(s), or an error message if the application(s) could not be fetched.
operationId: getApplication
security:
  - bearerAuth: []
parameters:
  - name: application_id
    in: path
    type: string
    required: false
    description: The ID of the application to fetch. If None, all applications are fetched.
responses:
  200:
    description: Application(s) fetched successfully
    examples:
      application/json:
        {
          "status": "success",
          "message": "Application fetched successfully",
          "data":
            [
              {
                "id": "application1",
                "job_id": "job1",
                "candidate_id": "candidate1",
                "status": "applied",
              },
              {
                "id": "application2",
                "job_id": "job2",
                "candidate_id": "candidate2",
                "status": "rejected",
              },
            ],
        }
  401:
    description: Unauthorized access
    examples:
      application/json:
        { "status": "error", "message": "Unauthorized", "data": {} }
  400:
    description: Invalid application ID
    examples:
      application/json:
        { "status": "error", "message": "Invalid application ID", "data": {} }
