securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

tags:
  - Applications
summary: Update an existing job application, Recruiters Only.
description: Endpoint to update an existing job application. The user must be authenticated, and the request data must contain the updated details of the application. Returns a JSON response containing the details of the updated application, or an error message if the application could not be updated.
operationId: updateApplication
security:
  - bearerAuth: []
parameters:
  - name: application_id
    in: path
    type: string
    required: true
    description: The ID of the application to update
  - in: body
    name: body
    schema:
      type: object
      properties:
        application_status:
          type: string
          description: The new status of the application
responses:
  200:
    description: Application updated successfully
    examples:
      application/json:
        {
          "status": "success",
          "message": "Application updated successfully",
          "data":
            {
              "id": "application1",
              "job_id": "job1",
              "candidate_id": "candidate1",
              "status": "accepted",
            },
        }
  401:
    description: Unauthorized access
    examples:
      application/json:
        { "status": "error", "message": "Unauthorized", "data": {} }
  400:
    description: Invalid application ID or status
    examples:
      application/json:
        {
          "status": "error",
          "message": "Invalid application ID or status",
          "data": {},
        }
