"""Define the common skills synonyms to help ensure consistency """

SKILL_SYNONYMS = {
    "python developer": "python",
    "professional in python": "python",
    "python programmer": "python",
    "expert in python": "python",
    "python engineer": "python",
    "python coder": "python",
    "data scientist": "data science",
    "machine learning engineer": "machine learning",
    "ML engineer": "machine learning",
    "artificial intelligence specialist": "artificial intelligence",
    "AI specialist": "artificial intelligence",
    "software engineer": "software engineering",
    "software developer": "software engineering",
    "full stack developer": "full stack development",
    "frontend developer": "frontend development",
    "backend developer": "backend development",
    "web developer": "web development",
    "JavaScript developer": "JavaScript",
    "Java developer": "Java",
    "C++ developer": "C++",
    "mobile app developer": "mobile development",
    "iOS developer": "iOS development",
    "Android developer": "Android development",
    "devops engineer": "DevOps",
    "cloud engineer": "cloud computing",
    "AWS specialist": "AWS",
    "Azure specialist": "Azure",
    "GCP specialist": "GCP",
    "cybersecurity expert": "cybersecurity",
    "information security analyst": "information security",
    "network administrator": "network administration",
    "system administrator": "system administration",
    "database administrator": "database administration",
    "DBA": "database administration",
    "data analyst": "data analysis",
    "data engineer": "data engineering",
    "big data specialist": "big data",
    "UI/UX designer": "UI/UX design",
    "graphic designer": "graphic design",
    "product manager": "product management",
    "project manager": "project management",
    "QA engineer": "quality assurance",
    "quality assurance engineer": "quality assurance",
    "test engineer": "quality assurance",
    "business analyst": "business analysis",
    "system analyst": "system analysis",
    "IT consultant": "IT consulting",
    "blockchain developer": "blockchain",
    "game developer": "game development",
    "embedded systems engineer": "embedded systems",
    "network engineer": "network engineering",
    "robotics engineer": "robotics",
    "AI researcher": "artificial intelligence research",
    "computer vision engineer": "computer vision",
    "natural language processing engineer": "NLP",
    "NLP engineer": "NLP",
    "bioinformatics specialist": "bioinformatics",
    "health informatics specialist": "health informatics",
    "IT support specialist": "IT support",
    "tech support": "IT support",
    "cybersecurity analyst": "cybersecurity",
    "information security specialist": "information security",
    "systems engineer": "system administration",
    "database manager": "database administration",
    "data specialist": "data engineering",
    "big data engineer": "big data",
    "UI designer": "UI/UX design",
    "UX designer": "UI/UX design",
    "product lead": "product management",
    "project lead": "project management",
    "QA specialist": "quality assurance",
    "test specialist": "quality assurance",
    "business consultant": "business analysis",
    "systems consultant": "system analysis",
    "IT advisor": "IT consulting",
    "blockchain specialist": "blockchain",
    "game designer": "game development",
    "embedded engineer": "embedded systems",
    "networking engineer": "network engineering",
    "robotics specialist": "robotics",
    "AI expert": "artificial intelligence research",
    "vision engineer": "computer vision",
    "NLP specialist": "NLP",
    "bioinformatics engineer": "bioinformatics",
    "health informatics engineer": "health informatics",
    "IT support engineer": "IT support",
    "technical support": "IT support",
    "Pythonista": "python",
    "Python professional": "python",
    "Data science analyst": "data science",
    "Data science engineer": "data science",
    "Machine learning specialist": "machine learning",
    "ML researcher": "machine learning",
    "Artificial intelligence engineer": "artificial intelligence",
    "AI developer": "artificial intelligence",
    "Software architect": "software engineering",
    "Application developer": "software engineering",
    "Front-end engineer": "frontend development",
    "Front end developer": "frontend development",
    "Back-end engineer": "backend development",
    "Back end developer": "backend development",
    "Web engineer": "web development",
    "Web programmer": "web development",
    "JS engineer": "JavaScript",
    "Java coder": "Java",
    "Java engineer": "Java",
    "C++ programmer": "C++",
    "Mobile developer": "mobile development",
    "Mobile application developer": "mobile development",
    "iOS programmer": "iOS development",
    "iOS engineer": "iOS development",
    "Android programmer": "Android development",
    "Android engineer": "Android development",
    "DevOps specialist": "DevOps",
    "Cloud specialist": "cloud computing",
    "AWS engineer": "AWS",
    "Azure engineer": "Azure",
    "GCP engineer": "GCP",
    "Cybersecurity specialist": "cybersecurity",
    "InfoSec analyst": "information security",
    "Network engineer": "network administration",
    "SysAdmin": "system administration",
    "Database admin": "database administration",
    "Data engineer": "data engineering",
    "Big data analyst": "big data",
    "UI/UX specialist": "UI/UX design",
    "UI/UX engineer": "UI/UX design",
    "Graphic artist": "graphic design",
    "Product owner": "product management",
    "Project coordinator": "project management",
    "QA tester": "quality assurance",
    "Test analyst": "quality assurance",
    "Business consultant": "business analysis",
    "Systems analyst": "system analysis",
    "IT advisor": "IT consulting",
    "Blockchain engineer": "blockchain",
    "Game programmer": "game development",
    "Game developer": "game development",
    "Embedded developer": "embedded systems",
    "Embedded engineer": "embedded systems",
    "Networking engineer": "network engineering",
    "Network specialist": "network engineering",
    "Robotics specialist": "robotics",
    "AI researcher": "artificial intelligence research",
    "Computer vision specialist": "computer vision",
    "NLP developer": "NLP",
    "NLP researcher": "NLP",
    "Bioinformatics researcher": "bioinformatics",
    "Health informatics researcher": "health informatics",
    "Tech support specialist": "IT support",
    "Technical support engineer": "IT support",
    "doctor": "physician",
    "medical doctor": "physician",
    "MD": "physician",
    "surgeon": "surgery",
    "general practitioner": "general practice",
    "GP": "general practice",
    "nurse": "nursing",
    "registered nurse": "nursing",
    "RN": "nursing",
    "dentist": "dentistry",
    "dental surgeon": "dentistry",
    "pharmacist": "pharmacy",
    "pharmacy specialist": "pharmacy",
    "radiologist": "radiology",
    "radiology specialist": "radiology",
    "cardiologist": "cardiology",
    "heart specialist": "cardiology",
    "oncologist": "oncology",
    "cancer specialist": "oncology",
    "psychiatrist": "psychiatry",
    "mental health specialist": "psychiatry",
    "pediatrician": "pediatrics",
    "child specialist": "pediatrics",
    "gynecologist": "gynecology",
    "obstetrician": "obstetrics",
    "OB-GYN": "obstetrics and gynecology",
    "orthopedic surgeon": "orthopedics",
    "physiotherapist": "physical therapy",
    "physical therapist": "physical therapy",
    "optometrist": "optometry",
    "eye specialist": "optometry",
    "dermatologist": "dermatology",
    "skin specialist": "dermatology",
    "anesthesiologist": "anesthesiology",
    "anesthesia specialist": "anesthesiology",
    "civil engineer": "civil engineering",
    "structural engineer": "structural engineering",
    "construction engineer": "construction engineering",
    "geotechnical engineer": "geotechnical engineering",
    "environmental engineer": "environmental engineering",
    "transportation engineer": "transportation engineering",
    "urban planner": "urban planning",
    "city planner": "urban planning",
    "highway engineer": "highway engineering",
    "bridge engineer": "bridge engineering",
    "water resources engineer": "water resources engineering",
    "hydraulic engineer": "hydraulic engineering",
    "surveying engineer": "surveying",
    "land surveyor": "surveying",
    "quantity surveyor": "quantity surveying",
    "site engineer": "site engineering",
    "project manager": "project management",
    "construction manager": "construction management",
    "mechanical engineer": "mechanical engineering",
    "automotive engineer": "automotive engineering",
    "aerospace engineer": "aerospace engineering",
    "aeronautical engineer": "aerospace engineering",
    "manufacturing engineer": "manufacturing engineering",
    "production engineer": "production engineering",
    "maintenance engineer": "maintenance engineering",
    "HVAC engineer": "HVAC engineering",
    "thermal engineer": "thermal engineering",
    "mechatronics engineer": "mechatronics",
    "robotics engineer": "robotics",
    "mechanical designer": "mechanical design",
    "CAD engineer": "computer-aided design",
    "CAE engineer": "computer-aided engineering",
    "automobile engineer": "automotive engineering",
    "industrial engineer": "industrial engineering",
    "materials engineer": "materials engineering",
    "metallurgical engineer": "metallurgy",
    "fluid dynamics engineer": "fluid dynamics",
    "acoustics engineer": "acoustics",
    "tribology engineer": "tribology",
    "electrical engineer": "electrical engineering",
    "electronics engineer": "electronics engineering",
    "power engineer": "power engineering",
    "control engineer": "control engineering",
    "signal processing engineer": "signal processing",
    "telecommunications engineer": "telecommunications",
    "RF engineer": "radio frequency engineering",
    "circuit designer": "circuit design",
    "embedded systems engineer": "embedded systems",
    "electrical designer": "electrical design",
    "microelectronics engineer": "microelectronics",
    "nanotechnology engineer": "nanotechnology",
    "semiconductor engineer": "semiconductor engineering",
    "PLC programmer": "PLC programming",
    "automation engineer": "automation engineering",
    "instrumentation engineer": "instrumentation engineering",
    "accountant": "accounting",
    "financial analyst": "financial analysis",
    "investment banker": "investment banking",
    "auditor": "auditing",
    "tax consultant": "taxation",
    "economist": "economics",
    "marketing manager": "marketing",
    "sales manager": "sales",
    "HR manager": "human resources",
    "recruitment specialist": "recruitment",
    "training specialist": "training",
    "legal advisor": "legal",
    "attorney": "lawyer",
    "paralegal": "legal assistant",
    "logistics manager": "logistics",
    "supply chain manager": "supply chain management",
    "procurement manager": "procurement",
    "warehouse manager": "warehouse management",
    "operations manager": "operations management",
    "business development manager": "business development",
    "strategy consultant": "strategy consulting",
    "management consultant": "management consulting",
    "customer service representative": "customer service",
    "support specialist": "customer support",
    "PR manager": "public relations",
    "communication specialist": "communications"
}
