"""Define the common skills synonyms to help ensure consistency """

SKILL_SYNONYMS = {
    "python developer": "python",
    "professional in python": "python",
    "python programmer": "python",
    "expert in python": "python",
    "python engineer": "python",
    "python coder": "python",
    "data scientist": "data science",
    "machine learning engineer": "machine learning",
    "ML engineer": "machine learning",
    "artificial intelligence specialist": "artificial intelligence",
    "AI specialist": "artificial intelligence",
    "software engineer": "software engineering",
    "software developer": "software engineering",
    "full stack developer": "full stack development",
    "frontend developer": "frontend development",
    "backend developer": "backend development",
    "web developer": "web development",
    "JavaScript developer": "JavaScript",
    "Java developer": "Java",
    "C++ developer": "C++",
    "mobile app developer": "mobile development",
    "iOS developer": "iOS development",
    "Android developer": "Android development",
    "devops engineer": "DevOps",
    "cloud engineer": "cloud computing",
    "AWS specialist": "AWS",
    "Azure specialist": "Azure",
    "GCP specialist": "GCP",
    "cybersecurity expert": "cybersecurity",
    "information security analyst": "information security",
    "network administrator": "network administration",
    "system administrator": "system administration",
    "database administrator": "database administration",
    "DBA": "database administration",
    "data analyst": "data analysis",
    "data engineer": "data engineering",
    "big data specialist": "big data",
    "UI/UX designer": "UI/UX design",
    "graphic designer": "graphic design",
    "product manager": "product management",
    "project manager": "project management",
    "QA engineer": "quality assurance",
    "quality assurance engineer": "quality assurance",
    "test engineer": "quality assurance",
    "business analyst": "business analysis",
    "system analyst": "system analysis",
    "IT consultant": "IT consulting",
    "blockchain developer": "blockchain",
    "game developer": "game development",
    "embedded systems engineer": "embedded systems",
    "network engineer": "network engineering",
    "robotics engineer": "robotics",
    "AI researcher": "artificial intelligence research",
    "computer vision engineer": "computer vision",
    "natural language processing engineer": "NLP",
    "NLP engineer": "NLP",
    "bioinformatics specialist": "bioinformatics",
    "health informatics specialist": "health informatics",
    "IT support specialist": "IT support",
    "tech support": "IT support",
    "cybersecurity analyst": "cybersecurity",
    "information security specialist": "information security",
    "systems engineer": "system administration",
    "database manager": "database administration",
    "data specialist": "data engineering",
    "big data engineer": "big data",
    "UI designer": "UI/UX design",
    "UX designer": "UI/UX design",
    "product lead": "product management",
    "project lead": "project management",
    "QA specialist": "quality assurance",
    "test specialist": "quality assurance",
    "business consultant": "business analysis",
    "systems consultant": "system analysis",
    "IT advisor": "IT consulting",
    "blockchain specialist": "blockchain",
    "game designer": "game development",
    "embedded engineer": "embedded systems",
    "networking engineer": "network engineering",
    "robotics specialist": "robotics",
    "AI expert": "artificial intelligence research",
    "vision engineer": "computer vision",
    "NLP specialist": "NLP",
    "bioinformatics engineer": "bioinformatics",
    "health informatics engineer": "health informatics",
    "IT support engineer": "IT support",
    "technical support": "IT support",
}
