export { default as MyIcon } from './Icon';
export { default as Upload } from './Upload';
export { default as ErrorPage } from './ErrorPage';
export { default as Private } from './Protected';
export { default as Layout } from './Layout';
export { default as Insights } from './Insights';
export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as MyModal } from './MyModal';
