securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

tags:
  - Applications
summary: Delete a job application
description: Endpoint to delete a job application. The user must be authenticated, and the ID of the application to delete must be provided. Returns a JSON response containing a success message if the application was deleted successfully, or an error message if the application could not be deleted.
operationId: deleteApplication
security:
  - bearerAuth: []
parameters:
  - name: application_id
    in: path
    type: string
    required: true
    description: The ID of the application to delete
responses:
  200:
    description: Application deleted successfully
  401:
    description: Unauthorized access
  400:
    description: Invalid application ID or application not found
