securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

tags:
  - Applications
security:
  - bearerAuth: []
parameters:
  - name: application_id
    in: path
    type: string
    required: false
    description: The ID of the application to fetch. If None, all applications are fetched.
responses:
  200:
    description: Application(s) fetched successfully
  401:
    description: Unauthorized access
  400:
    description: Invalid application ID
