securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

tags:
  - Applications
security:
  - bearerAuth: []
parameters:
  - name: application_id
    in: path
    type: string
    required: true
    description: The ID of the application to update
  - in: body
    name: body
    schema:
      type: object
      properties:
        status:
          type: string
          description: The new status of the application
responses:
  200:
    description: Application updated successfully
  401:
    description: Unauthorized access
  400:
    description: Invalid application ID or status
