export const college_majors = [
  "Accounting",
  "Agricultural Business",
  "Agricultural Economics",
  "Agricultural Education",
  "Agricultural Engineering",
  "Agricultural Science",
  "Agriculture",
  "Animal Science",
  "Anthropology",
  "Applied Mathematics",
  "Architecture",
  "Art History",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biotechnology",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classical Studies",
  "Communications",
  "Computer Engineering",
  "Computer Science",
  "Criminal Justice",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Dental Hygiene",
  "Drama",
  "Early Childhood Education",
  "Economics",
  "Electrical Engineering",
  "Elementary Education",
  "English",
  "Environmental Engineering",
  "Environmental Science",
  "Fashion Design",
  "Film Studies",
  "Finance",
  "Fine Arts",
  "Food Science",
  "Forensic Science",
  "French",
  "Genetics",
  "Geography",
  "Geology",
  "Graphic Design",
  "Health Administration",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Industrial Engineering",
  "Information Systems",
  "International Relations",
  "Journalism",
  "Landscape Architecture",
  "Law",
  "Linguistics",
  "Management",
  "Marketing",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Technology",
  "Microbiology",
  "Music",
  "Nursing",
  "Nutrition",
  "Philosophy",
  "Photography",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Public Relations",
  "Secondary Education",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Spanish",
  "Special Education",
  "Sports Management",
  "Statistics",
  "Supply Chain Management",
  "Theater",
  "Urban Planning",
  "Veterinary Science",
  "Zoology",
];

export const skills = [
  "Communication",
  "Teamwork",
  "Problem solving",
  "Time Management",
  "Leadership",
  "Attention to Detail",
  "Microsoft Office",
  "Customer Service",
  "Project Management",
  "Sales",
  "Marketing",
  "Public Speaking",
  "Negotiation",
  "Conflict Resolution",
  "Visual Design",
  "Data Analysis",
  "Programming",
  "Foreign Languages",
  "Networking",
  "Mathematics",
  "SEO/SEM Marketing",
  "Accounting",
  "Graphic Design",
  "Event Planning",
  "Social Media Management",
  "Technical Writing",
  "Research",
  "Enterprise Systems (ERP/SAP)",
  "Mobile Development",
  "Data Presentation",
  "UX/UI Design",
  "Software QA and User Testing",
  "Data Engineering",
  "Web Development",
  "AI and Machine Learning",
  "Database Management",
  "Cloud Computing",
  "Statistical Analysis",
  "Data Visualization",
  "Information Security",
  "Networking",
  "Software Development",
  "Business Intelligence",
  "Storage Systems and Management",
  "Telecommunications",
  "Virtualization",
  "Wireless Networking",
  "SEO/SEM Marketing",
  "Data Presentation",
  "Mobile Development",
  "UX/UI Design",
  "Software QA and User Testing",
  "Data Engineering",
  "Web Development",
  "AI and Machine Learning",
  "Database Management",
  "Cloud Computing",
  "Statistical Analysis",
  "Data Visualization",
  "Information Security",
  "Networking",
  "Software Development",
  "Business Intelligence",
  "Storage Systems and Management",
  "Telecommunications",
  "Virtualization",
  "Wireless Networking",
];

export const languages = [
  "Arabic",
  "Bengali",
  "Chinese",
  "Dutch",
  "English",
  "French",
  "German",
  "Greek",
  "Hindi",
  "Italian",
  "Japanese",
  "Korean",
  "Latin",
  "Malay",
  "Norwegian",
  "Polish",
  "Portuguese",
  "Russian",
  "Spanish",
  "Swedish",
  "Thai",
  "Turkish",
  "Urdu",
  "Vietnamese",
  "Welsh",
  "Zulu",
];
