export const college_majors = [
  "Accounting",
  "Agricultural Business",
  "Agricultural Economics",
  "Agricultural Education",
  "Agricultural Engineering",
  "Agricultural Science",
  "Agriculture",
  "Animal Science",
  "Anthropology",
  "Applied Mathematics",
  "Architecture",
  "Art History",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biotechnology",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classical Studies",
  "Communications",
  "Computer Engineering",
  "Computer Science",
  "Criminal Justice",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Dental Hygiene",
  "Drama",
  "Early Childhood Education",
  "Economics",
  "Electrical Engineering",
  "Elementary Education",
  "English",
  "Environmental Engineering",
  "Environmental Science",
  "Fashion Design",
  "Film Studies",
  "Finance",
  "Fine Arts",
  "Food Science",
  "Forensic Science",
  "French",
  "Genetics",
  "Geography",
  "Geology",
  "Graphic Design",
  "Health Administration",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Industrial Engineering",
  "Information Systems",
  "International Relations",
  "Journalism",
  "Landscape Architecture",
  "Law",
  "Linguistics",
  "Management",
  "Marketing",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Technology",
  "Microbiology",
  "Music",
  "Nursing",
  "Nutrition",
  "Philosophy",
  "Photography",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Public Relations",
  "Secondary Education",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Spanish",
  "Special Education",
  "Sports Management",
  "Statistics",
  "Supply Chain Management",
  "Theater",
  "Urban Planning",
  "Veterinary Science",
  "Zoology",
];

export const FAQS = [
  { 'how does job linker work for recruiter': 'Recruiters can easily post their job descriptions on Job Linker and our platform will match them with qualified candidates.' },
  { 'Can candidates apply directly through Job Linker?': 'Yes, candidates can apply directly through Job Linker. They will be matched with job postings based on their qualifications.' },
  { 'Is Job Linker free to use for both recruiters and candidates?': 'Yes, Job Linker is completely free for both recruiters and candidates to use.' },
  { 'How are candidates matched with job postings on Job Linker?': 'Candidates are matched based on their qualifications and the job requirements provided by the recruiters.' },
  { 'Can recruiters contact candidates directly through Job Linker?': "Yes, recruiters can contact matched candidates directly through Job Linker's messaging system." }
];
