export const college_majors = [
  'Accounting',
  'Agricultural Business',
  'Agricultural Economics',
  'Agricultural Education',
  'Agricultural Engineering',
  'Agricultural Science',
  'Agriculture',
  'Animal Science',
  'Anthropology',
  'Applied Mathematics',
  'Architecture',
  'Art History',
  'Astronomy',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Biotechnology',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Classical Studies',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Criminal Justice',
  'Cybersecurity',
  'Dance',
  'Data Science',
  'Dental Hygiene',
  'Drama',
  'Early Childhood Education',
  'Economics',
  'Electrical Engineering',
  'Elementary Education',
  'English',
  'Environmental Engineering',
  'Environmental Science',
  'Fashion Design',
  'Film Studies',
  'Finance',
  'Fine Arts',
  'Food Science',
  'Forensic Science',
  'French',
  'Genetics',
  'Geography',
  'Geology',
  'Graphic Design',
  'Health Administration',
  'History',
  'Hospitality Management',
  'Human Resources',
  'Industrial Engineering',
  'Information Systems',
  'International Relations',
  'Journalism',
  'Landscape Architecture',
  'Law',
  'Linguistics',
  'Management',
  'Marketing',
  'Materials Science',
  'Mathematics',
  'Mechanical Engineering',
  'Medical Technology',
  'Microbiology',
  'Music',
  'Nursing',
  'Nutrition',
  'Philosophy',
  'Photography',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Public Relations',
  'Secondary Education',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Spanish',
  'Special Education',
  'Sports Management',
  'Statistics',
  'Supply Chain Management',
  'Theater',
  'Urban Planning',
  'Veterinary Science',
  'Zoology'
]
